language: c++
compiler:
  - clang
jobs:
  - PATH="/usr/local/opt/qt/bin:$PATH"
  - LDFLAGS="-L/usr/local/opt/qt/lib"
  - CPPFLAGS="-I/usr/local/opt/qt/include"
  - PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
    - qt
    update: true
before_script:
  - ls /usr/local/opt/qt/bin
  - ls -la ~/
  - echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  - mkdir build
  - ls -la
  - cd build
script:
  - cmake ..
