language: c++
os: osx
osx_image: xcode12.2
env:
  global:
    - DEPLOY_VERSION=$(<version.txt)
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - libarchive
      - curl
      - qt
    update: true
before_script:
  - brew upgrade qt
  - mkdir build
  - ls -la
  - cd build
script:
  - |
    cmake \
    -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
    -DLibArchive_INCLUDE_DIR=$(brew --prefix libarchive)/include \
    -DLibArchive_LIBRARIES=$(brew --prefix libarchive)/lib \
    ..
  - echo "${DEPLOY_VERSION}"
  - export DEPLOY_TAG="v${DEPLOY_VERSION}-alpha"
  - export DEPLOY_FILE_NAME="ReleaseInstaller-${DEPLOY_VERSION}-Darwin.dmg"
  - export DEPLOY_NAME="Release Installer ${DEPLOY_VERSION}"
  - printenv
  - make
  - cpack -G DragNDrop
  - cpack -G Bundle
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "lmsorenson"
  - git config --local user.email "lsorenson20@gmail.com"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: ${DEPLOY_FILE_NAME}
  cleanup: false
  name: ${DEPLOY_NAME}
  body: "First try"
  tag_name: ${DEPLOY_TAG}
  prerelease: true
