language: c++
compiler:
  - clang
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - libarchive
      - curl
      - qt
    update: true
before_script:
  - mkdir build
  - ls -la
  - cd build
script:
  - |
    cmake \
    -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
    -DLibArchive_INCLUDE_DIR=$(brew --prefix libarchive)/include \
    -DLibArchive_LIBRARIES=$(brew --prefix libarchive)/lib \
    ..
  - make
  - cpack -G DragNDrop