language: c++
os: osx
osx_image: xcode12.2
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
      - libarchive
      - curl
      - qt
    update: true
before_script:
  - brew upgrade qt
  - mkdir build
  - ls -la
  - cd build
script:
  - |
    cmake \
    -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 \
    -DLibArchive_INCLUDE_DIR=$(brew --prefix libarchive)/include \
    -DLibArchive_LIBRARIES=$(brew --prefix libarchive)/lib \
    ..
    echo "ENV " + ${RELEASE_INSTALLER_VERSION}
  - make
  - cpack -G DragNDrop
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "lmsorenson"
  - git config --local user.email "lsorenson20@gmail.com"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG
  - export TRAVIS_TAG=concat("v", env(RELEASE_INSTALLER_VERSION), "-alpha")
  - export RELEASE_FILE_NAME=concat("ReleaseInstaller-", env(RELEASE_INSTALLER_VERSION), "-Darwin.dmg")
  - export RELEASE_NAME=env(RELEASE_INSTALLER_VERSION)
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: ${RELEASE_FILE_NAME}
  skip_cleanup: true
  name: ${RELEASE_NAME}
  body: "First try"
  tag_name: ${TRAVIS_TAG}
  prerelease: true
