language: c++
compiler:
  - clang
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
addons:
  homebrew:
    packages:
    - qt
    update: true
before_script:
  - echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  - mkdir build
  - ls -la
  - cd build
script:
  - cmake ..
