language: c++
compiler:
  - clang
os:
  - osx
    osx_image: xcode12.2
addons:
  homebrew:
    packages:
    - qt
    update: true
before_script:
  - mkdir build
  - ls -la
  - cd build
script:
  - cmake ..
